import type { CatalogProduct, CatalogProductDetails } from "./catalog.types";

function skinDetails(productType: string, condition: string, floatValue?: string, game = "Counter-Strike 2"): CatalogProductDetails {
  return {
    specifications: [
      { label: "Игра", value: game },
      { label: "Тип", value: productType },
      { label: "Состояние", value: condition },
      ...(floatValue ? [{ label: "Float", value: floatValue }] : []),
    ],
    fulfillment: {
      title: "Данные Steam Trade",
      description: "Товар и Trade URL фиксируются в заказе. Внешняя передача через Steam будет выполняться только после подключения SIH fulfillment.",
      requirements: [
        "Для оформления игрового предмета требуется Steam-сессия.",
        "Укажите действующий Steam Trade URL перед оформлением заказа.",
        "Перед provider-выдачей заказ пройдет повторную проверку цены и доступности.",
      ],
    },
  };
}

function steamTopUpDetails(nominal: string): CatalogProductDetails {
  return {
    specifications: [
      { label: "Сервис", value: "Steam" },
      { label: "Тип", value: "Пополнение баланса" },
      { label: "Зачисление в Steam", value: nominal },
    ],
    fulfillment: {
      title: "Данные пополнения Steam",
      description: "Логин Steam фиксируется в заказе. Зачисление будет выполняться provider-адаптером после подключения SIH fulfillment.",
      requirements: [
        "Проверьте логин Steam перед оплатой.",
        "Стоимость фиксируется в Coins по курсу Vault.",
        "Перед отправкой провайдеру заказ пройдет повторную проверку статуса.",
      ],
    },
  };
}

const coinRateLabel = "1 RUB = 1.5 Coins";

export const firstReleaseCatalogProducts: CatalogProduct[] = [
  {
    id: "ak-redline",
    slug: "ak-47-redline",
    kind: "skins",
    category: "Игровые предметы",
    game: "CS2",
    productType: "Автомат",
    title: "AK-47 | Redline",
    description: "AK-47 с контрастным красно-черным оформлением для Counter-Strike 2. Версия после полевых испытаний, Float 0.21.",
    priceCoins: 2840,
    availability: "available",
    fulfillmentMode: "steam-trade",
    createdAt: "2026-05-28T10:00:00.000Z",
    popularity: 100,
    image: "/products/ak-redline.png",
    imageAlt: "AK-47 Redline из Counter-Strike 2",
    meta: ["CS2", "Field-Tested", "Float 0.21"],
    keywords: ["автомат", "винтовка", "оружие", "cs2"],
    details: skinDetails("Автомат", "После полевых испытаний", "0.21"),
  },
  {
    id: "awp-asiimov",
    slug: "awp-asiimov",
    kind: "skins",
    category: "Игровые предметы",
    game: "CS2",
    productType: "Снайперская винтовка",
    title: "AWP | Asiimov",
    description: "AWP в оранжево-белой расцветке Asiimov для Counter-Strike 2. Состояние закаленное в боях, Float 0.53.",
    priceCoins: 6950,
    availability: "available",
    fulfillmentMode: "steam-trade",
    createdAt: "2026-06-04T10:00:00.000Z",
    popularity: 96,
    image: "/products/awp-asiimov.png",
    imageAlt: "AWP Asiimov из Counter-Strike 2",
    meta: ["CS2", "Battle-Scarred", "Float 0.53"],
    keywords: ["снайперская", "винтовка", "оружие", "cs2"],
    details: skinDetails("Снайперская винтовка", "Закаленное в боях", "0.53"),
  },
  {
    id: "m4-printstream",
    slug: "m4a1-s-printstream",
    kind: "skins",
    category: "Игровые предметы",
    game: "CS2",
    productType: "Автомат",
    title: "M4A1-S | Printstream",
    description: "M4A1-S Printstream с глушителем и светлым графическим оформлением для Counter-Strike 2. Версия после полевых испытаний, Float 0.19.",
    priceCoins: 7420,
    availability: "available",
    fulfillmentMode: "steam-trade",
    createdAt: "2026-06-18T10:00:00.000Z",
    popularity: 94,
    image: "/products/m4-printstream.png",
    imageAlt: "M4A1-S Printstream из Counter-Strike 2",
    meta: ["CS2", "Field-Tested", "Float 0.19"],
    keywords: ["автомат", "винтовка", "оружие", "cs2"],
    details: skinDetails("Автомат", "После полевых испытаний", "0.19"),
  },
  {
    id: "deagle-printstream",
    slug: "desert-eagle-printstream",
    kind: "skins",
    category: "Игровые предметы",
    game: "CS2",
    productType: "Пистолет",
    title: "Desert Eagle | Printstream",
    description: "Desert Eagle Printstream с минимальным износом для Counter-Strike 2. Float 0.11 и светлая отделка.",
    priceCoins: 3180,
    availability: "available",
    fulfillmentMode: "steam-trade",
    createdAt: "2026-06-25T10:00:00.000Z",
    popularity: 91,
    image: "/products/deagle-printstream.png",
    imageAlt: "Desert Eagle Printstream из Counter-Strike 2",
    meta: ["CS2", "Minimal Wear", "Float 0.11"],
    keywords: ["пистолет", "оружие", "cs2"],
    details: skinDetails("Пистолет", "Немного поношенное", "0.11"),
  },
  {
    id: "dota-pa-manifold-paradox",
    slug: "dota-2-manifold-paradox-phantom-assassin",
    kind: "skins",
    category: "Игровые предметы",
    game: "Dota 2",
    productType: "Arcana",
    title: "Manifold Paradox | Phantom Assassin",
    description: "Arcana Manifold Paradox для Phantom Assassin в Dota 2 с альтернативными эффектами и узнаваемым комплектом героя.",
    priceCoins: 4650,
    availability: "available",
    fulfillmentMode: "steam-trade",
    createdAt: "2026-05-12T10:00:00.000Z",
    popularity: 63,
    meta: ["Dota 2", "Arcana", "Phantom Assassin"],
    keywords: ["dota", "dota 2", "дота", "arcana", "phantom assassin", "скин"],
    details: skinDetails("Arcana", "Стандартное", undefined, "Dota 2"),
  },
  {
    id: "dota-pudge-feast-of-abscession",
    slug: "dota-2-feast-of-abscession-pudge",
    kind: "skins",
    category: "Игровые предметы",
    game: "Dota 2",
    productType: "Arcana",
    title: "Feast of Abscession | Pudge",
    description: "Arcana Feast of Abscession для Pudge в Dota 2 с тематическими визуальными эффектами героя.",
    priceCoins: 3980,
    availability: "available",
    fulfillmentMode: "steam-trade",
    createdAt: "2026-04-26T10:00:00.000Z",
    popularity: 59,
    meta: ["Dota 2", "Arcana", "Pudge"],
    keywords: ["dota", "dota 2", "дота", "arcana", "pudge", "скин"],
    details: skinDetails("Arcana", "Стандартное", undefined, "Dota 2"),
  },
  {
    id: "rust-tempered-ak47",
    slug: "rust-tempered-ak47",
    kind: "skins",
    category: "Игровые предметы",
    game: "Rust",
    productType: "Винтовка",
    title: "Tempered AK47",
    description: "Tempered AK47 - скин штурмовой винтовки для Rust с металлическим закаленным рисунком.",
    priceCoins: 3290,
    availability: "available",
    fulfillmentMode: "steam-trade",
    createdAt: "2026-05-06T10:00:00.000Z",
    popularity: 57,
    meta: ["Rust", "Assault Rifle", "Tempered"],
    keywords: ["rust", "раст", "ak47", "винтовка", "скин"],
    details: skinDetails("Винтовка", "Стандартное", undefined, "Rust"),
  },
  {
    id: "rust-alien-red-ak",
    slug: "rust-alien-red-ak",
    kind: "skins",
    category: "Игровые предметы",
    game: "Rust",
    productType: "Винтовка",
    title: "Alien Red AK",
    description: "Alien Red AK - коллекционный скин штурмовой винтовки для Rust в красной цветовой схеме.",
    priceCoins: 5840,
    availability: "available",
    fulfillmentMode: "steam-trade",
    createdAt: "2026-04-18T10:00:00.000Z",
    popularity: 54,
    meta: ["Rust", "Assault Rifle", "Alien Red"],
    keywords: ["rust", "раст", "alien red", "ak", "винтовка", "скин"],
    details: skinDetails("Винтовка", "Стандартное", undefined, "Rust"),
  },
  {
    id: "steam-top-up-500",
    slug: "steam-top-up-500-rub",
    kind: "steam",
    category: "Steam",
    game: "Steam",
    productType: "Пополнение баланса",
    title: "Пополнение Steam на 500 RUB",
    description: "Пополнение кошелька Steam на 500 RUB с пересчетом в Coins по фиксированному курсу Vault.",
    priceCoins: 750,
    availability: "available",
    fulfillmentMode: "automatic",
    createdAt: "2026-05-20T10:00:00.000Z",
    popularity: 86,
    meta: [coinRateLabel, "Steam", "RUB"],
    keywords: ["стим", "кошелек", "баланс", "пополнение"],
    details: steamTopUpDetails("500 RUB"),
  },
  {
    id: "steam-top-up-1000",
    slug: "steam-top-up-1000-rub",
    kind: "steam",
    category: "Steam",
    game: "Steam",
    productType: "Пополнение баланса",
    title: "Пополнение Steam на 1000 RUB",
    description: "Пополнение кошелька Steam на 1000 RUB по курсу Vault. Перед оформлением проверьте логин.",
    priceCoins: 1500,
    availability: "available",
    fulfillmentMode: "automatic",
    createdAt: "2026-06-02T10:00:00.000Z",
    popularity: 90,
    meta: [coinRateLabel, "Steam", "RUB"],
    keywords: ["стим", "кошелек", "баланс", "пополнение"],
    details: steamTopUpDetails("1000 RUB"),
  },
  {
    id: "steam-top-up-2000",
    slug: "steam-top-up-2000-rub",
    kind: "steam",
    category: "Steam",
    game: "Steam",
    productType: "Пополнение баланса",
    title: "Пополнение Steam на 2000 RUB",
    description: "Пополнение кошелька Steam на 2000 RUB. Стоимость фиксируется в Coins, логин сохраняется в заказе.",
    priceCoins: 3000,
    availability: "available",
    fulfillmentMode: "automatic",
    createdAt: "2026-06-20T10:00:00.000Z",
    popularity: 84,
    meta: [coinRateLabel, "Steam", "RUB"],
    keywords: ["стим", "кошелек", "баланс", "пополнение"],
    details: steamTopUpDetails("2000 RUB"),
  },
  {
    id: "steam-top-up-5000",
    slug: "steam-top-up-5000-rub",
    kind: "steam",
    category: "Steam",
    game: "Steam",
    productType: "Пополнение баланса",
    title: "Пополнение Steam на 5000 RUB",
    description: "Пополнение кошелька Steam на 5000 RUB с расчетом по курсу Vault.",
    priceCoins: 7500,
    availability: "available",
    fulfillmentMode: "automatic",
    createdAt: "2026-07-01T10:00:00.000Z",
    popularity: 78,
    meta: [coinRateLabel, "Steam", "RUB"],
    keywords: ["стим", "кошелек", "баланс", "пополнение"],
    details: steamTopUpDetails("5000 RUB"),
  },
];
