CREATE TABLE "catalog_products" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"kind" text NOT NULL,
	"category" text NOT NULL,
	"game" text,
	"product_type" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"price_coin_minor" integer NOT NULL,
	"availability" text NOT NULL,
	"fulfillment_mode" text NOT NULL,
	"popularity" integer NOT NULL,
	"image" text,
	"image_alt" text,
	"meta" text[] NOT NULL,
	"keywords" text[] NOT NULL,
	"details" jsonb NOT NULL,
	"supplier_provider" text,
	"supplier_item_id" text,
	"supplier_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"supplier_fresh_at" timestamp with time zone,
	"public_enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "catalog_products_slug_uidx" ON "catalog_products" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "catalog_products_kind_public_idx" ON "catalog_products" USING btree ("kind","public_enabled");--> statement-breakpoint
CREATE INDEX "catalog_products_game_idx" ON "catalog_products" USING btree ("game");--> statement-breakpoint
CREATE INDEX "catalog_products_product_type_idx" ON "catalog_products" USING btree ("product_type");--> statement-breakpoint
INSERT INTO "catalog_products" (
  "id",
  "slug",
  "kind",
  "category",
  "game",
  "product_type",
  "title",
  "description",
  "price_coin_minor",
  "availability",
  "fulfillment_mode",
  "popularity",
  "image",
  "image_alt",
  "meta",
  "keywords",
  "details",
  "supplier_provider",
  "supplier_snapshot",
  "public_enabled",
  "created_at"
) VALUES
(
  'ak-redline',
  'ak-47-redline',
  'skins',
  'Игровые предметы',
  'CS2',
  'Автомат',
  'AK-47 | Redline',
  'AK-47 с контрастным красно-черным оформлением для Counter-Strike 2. Версия после полевых испытаний, Float 0.21.',
  284000,
  'available',
  'steam-trade',
  100,
  '/products/ak-redline.png',
  'AK-47 Redline из Counter-Strike 2',
  ARRAY['CS2', 'Field-Tested', 'Float 0.21'],
  ARRAY['автомат', 'винтовка', 'оружие', 'cs2'],
  '{"specifications":[{"label":"Игра","value":"Counter-Strike 2"},{"label":"Тип","value":"Автомат"},{"label":"Состояние","value":"После полевых испытаний"},{"label":"Float","value":"0.21"}],"fulfillment":{"title":"Данные Steam Trade","description":"Товар и Trade URL фиксируются в заказе. Внешняя передача через Steam будет выполняться только после подключения SIH fulfillment.","requirements":["Для оформления игрового предмета требуется Steam-сессия.","Укажите действующий Steam Trade URL перед оформлением заказа.","Перед provider-выдачей заказ пройдет повторную проверку цены и доступности."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-05-28T10:00:00.000Z'
),
(
  'awp-asiimov',
  'awp-asiimov',
  'skins',
  'Игровые предметы',
  'CS2',
  'Снайперская винтовка',
  'AWP | Asiimov',
  'AWP в оранжево-белой расцветке Asiimov для Counter-Strike 2. Состояние закаленное в боях, Float 0.53.',
  695000,
  'available',
  'steam-trade',
  96,
  '/products/awp-asiimov.png',
  'AWP Asiimov из Counter-Strike 2',
  ARRAY['CS2', 'Battle-Scarred', 'Float 0.53'],
  ARRAY['снайперская', 'винтовка', 'оружие', 'cs2'],
  '{"specifications":[{"label":"Игра","value":"Counter-Strike 2"},{"label":"Тип","value":"Снайперская винтовка"},{"label":"Состояние","value":"Закаленное в боях"},{"label":"Float","value":"0.53"}],"fulfillment":{"title":"Данные Steam Trade","description":"Товар и Trade URL фиксируются в заказе. Внешняя передача через Steam будет выполняться только после подключения SIH fulfillment.","requirements":["Для оформления игрового предмета требуется Steam-сессия.","Укажите действующий Steam Trade URL перед оформлением заказа.","Перед provider-выдачей заказ пройдет повторную проверку цены и доступности."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-06-04T10:00:00.000Z'
),
(
  'm4-printstream',
  'm4a1-s-printstream',
  'skins',
  'Игровые предметы',
  'CS2',
  'Автомат',
  'M4A1-S | Printstream',
  'M4A1-S Printstream с глушителем и светлым графическим оформлением для Counter-Strike 2. Версия после полевых испытаний, Float 0.19.',
  742000,
  'available',
  'steam-trade',
  94,
  '/products/m4-printstream.png',
  'M4A1-S Printstream из Counter-Strike 2',
  ARRAY['CS2', 'Field-Tested', 'Float 0.19'],
  ARRAY['автомат', 'винтовка', 'оружие', 'cs2'],
  '{"specifications":[{"label":"Игра","value":"Counter-Strike 2"},{"label":"Тип","value":"Автомат"},{"label":"Состояние","value":"После полевых испытаний"},{"label":"Float","value":"0.19"}],"fulfillment":{"title":"Данные Steam Trade","description":"Товар и Trade URL фиксируются в заказе. Внешняя передача через Steam будет выполняться только после подключения SIH fulfillment.","requirements":["Для оформления игрового предмета требуется Steam-сессия.","Укажите действующий Steam Trade URL перед оформлением заказа.","Перед provider-выдачей заказ пройдет повторную проверку цены и доступности."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-06-18T10:00:00.000Z'
),
(
  'deagle-printstream',
  'desert-eagle-printstream',
  'skins',
  'Игровые предметы',
  'CS2',
  'Пистолет',
  'Desert Eagle | Printstream',
  'Desert Eagle Printstream с минимальным износом для Counter-Strike 2. Float 0.11 и светлая отделка.',
  318000,
  'available',
  'steam-trade',
  91,
  '/products/deagle-printstream.png',
  'Desert Eagle Printstream из Counter-Strike 2',
  ARRAY['CS2', 'Minimal Wear', 'Float 0.11'],
  ARRAY['пистолет', 'оружие', 'cs2'],
  '{"specifications":[{"label":"Игра","value":"Counter-Strike 2"},{"label":"Тип","value":"Пистолет"},{"label":"Состояние","value":"Немного поношенное"},{"label":"Float","value":"0.11"}],"fulfillment":{"title":"Данные Steam Trade","description":"Товар и Trade URL фиксируются в заказе. Внешняя передача через Steam будет выполняться только после подключения SIH fulfillment.","requirements":["Для оформления игрового предмета требуется Steam-сессия.","Укажите действующий Steam Trade URL перед оформлением заказа.","Перед provider-выдачей заказ пройдет повторную проверку цены и доступности."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-06-25T10:00:00.000Z'
),
(
  'dota-pa-manifold-paradox',
  'dota-2-manifold-paradox-phantom-assassin',
  'skins',
  'Игровые предметы',
  'Dota 2',
  'Arcana',
  'Manifold Paradox | Phantom Assassin',
  'Arcana Manifold Paradox для Phantom Assassin в Dota 2 с альтернативными эффектами и узнаваемым комплектом героя.',
  465000,
  'available',
  'steam-trade',
  63,
  NULL,
  NULL,
  ARRAY['Dota 2', 'Arcana', 'Phantom Assassin'],
  ARRAY['dota', 'dota 2', 'дота', 'arcana', 'phantom assassin', 'скин'],
  '{"specifications":[{"label":"Игра","value":"Dota 2"},{"label":"Тип","value":"Arcana"},{"label":"Состояние","value":"Стандартное"}],"fulfillment":{"title":"Данные Steam Trade","description":"Товар и Trade URL фиксируются в заказе. Внешняя передача через Steam будет выполняться только после подключения SIH fulfillment.","requirements":["Для оформления игрового предмета требуется Steam-сессия.","Укажите действующий Steam Trade URL перед оформлением заказа.","Перед provider-выдачей заказ пройдет повторную проверку цены и доступности."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-05-12T10:00:00.000Z'
),
(
  'dota-pudge-feast-of-abscession',
  'dota-2-feast-of-abscession-pudge',
  'skins',
  'Игровые предметы',
  'Dota 2',
  'Arcana',
  'Feast of Abscession | Pudge',
  'Arcana Feast of Abscession для Pudge в Dota 2 с тематическими визуальными эффектами героя.',
  398000,
  'available',
  'steam-trade',
  59,
  NULL,
  NULL,
  ARRAY['Dota 2', 'Arcana', 'Pudge'],
  ARRAY['dota', 'dota 2', 'дота', 'arcana', 'pudge', 'скин'],
  '{"specifications":[{"label":"Игра","value":"Dota 2"},{"label":"Тип","value":"Arcana"},{"label":"Состояние","value":"Стандартное"}],"fulfillment":{"title":"Данные Steam Trade","description":"Товар и Trade URL фиксируются в заказе. Внешняя передача через Steam будет выполняться только после подключения SIH fulfillment.","requirements":["Для оформления игрового предмета требуется Steam-сессия.","Укажите действующий Steam Trade URL перед оформлением заказа.","Перед provider-выдачей заказ пройдет повторную проверку цены и доступности."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-04-26T10:00:00.000Z'
),
(
  'rust-tempered-ak47',
  'rust-tempered-ak47',
  'skins',
  'Игровые предметы',
  'Rust',
  'Винтовка',
  'Tempered AK47',
  'Tempered AK47 - скин штурмовой винтовки для Rust с металлическим закаленным рисунком.',
  329000,
  'available',
  'steam-trade',
  57,
  NULL,
  NULL,
  ARRAY['Rust', 'Assault Rifle', 'Tempered'],
  ARRAY['rust', 'раст', 'ak47', 'винтовка', 'скин'],
  '{"specifications":[{"label":"Игра","value":"Rust"},{"label":"Тип","value":"Винтовка"},{"label":"Состояние","value":"Стандартное"}],"fulfillment":{"title":"Данные Steam Trade","description":"Товар и Trade URL фиксируются в заказе. Внешняя передача через Steam будет выполняться только после подключения SIH fulfillment.","requirements":["Для оформления игрового предмета требуется Steam-сессия.","Укажите действующий Steam Trade URL перед оформлением заказа.","Перед provider-выдачей заказ пройдет повторную проверку цены и доступности."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-05-06T10:00:00.000Z'
),
(
  'rust-alien-red-ak',
  'rust-alien-red-ak',
  'skins',
  'Игровые предметы',
  'Rust',
  'Винтовка',
  'Alien Red AK',
  'Alien Red AK - коллекционный скин штурмовой винтовки для Rust в красной цветовой схеме.',
  584000,
  'available',
  'steam-trade',
  54,
  NULL,
  NULL,
  ARRAY['Rust', 'Assault Rifle', 'Alien Red'],
  ARRAY['rust', 'раст', 'alien red', 'ak', 'винтовка', 'скин'],
  '{"specifications":[{"label":"Игра","value":"Rust"},{"label":"Тип","value":"Винтовка"},{"label":"Состояние","value":"Стандартное"}],"fulfillment":{"title":"Данные Steam Trade","description":"Товар и Trade URL фиксируются в заказе. Внешняя передача через Steam будет выполняться только после подключения SIH fulfillment.","requirements":["Для оформления игрового предмета требуется Steam-сессия.","Укажите действующий Steam Trade URL перед оформлением заказа.","Перед provider-выдачей заказ пройдет повторную проверку цены и доступности."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-04-18T10:00:00.000Z'
),
(
  'steam-top-up-500',
  'steam-top-up-500-rub',
  'steam',
  'Steam',
  'Steam',
  'Пополнение баланса',
  'Пополнение Steam на 500 RUB',
  'Пополнение кошелька Steam на 500 RUB с пересчетом в Coins по фиксированному курсу Vault.',
  75000,
  'available',
  'automatic',
  86,
  NULL,
  NULL,
  ARRAY['1 RUB = 1.5 Coins', 'Steam', 'RUB'],
  ARRAY['стим', 'кошелек', 'баланс', 'пополнение'],
  '{"specifications":[{"label":"Сервис","value":"Steam"},{"label":"Тип","value":"Пополнение баланса"},{"label":"Зачисление в Steam","value":"500 RUB"}],"fulfillment":{"title":"Данные пополнения Steam","description":"Логин Steam фиксируется в заказе. Зачисление будет выполняться provider-адаптером после подключения SIH fulfillment.","requirements":["Проверьте логин Steam перед оплатой.","Стоимость фиксируется в Coins по курсу Vault.","Перед отправкой провайдеру заказ пройдет повторную проверку статуса."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-05-20T10:00:00.000Z'
),
(
  'steam-top-up-1000',
  'steam-top-up-1000-rub',
  'steam',
  'Steam',
  'Steam',
  'Пополнение баланса',
  'Пополнение Steam на 1000 RUB',
  'Пополнение кошелька Steam на 1000 RUB по курсу Vault. Перед оформлением проверьте логин.',
  150000,
  'available',
  'automatic',
  90,
  NULL,
  NULL,
  ARRAY['1 RUB = 1.5 Coins', 'Steam', 'RUB'],
  ARRAY['стим', 'кошелек', 'баланс', 'пополнение'],
  '{"specifications":[{"label":"Сервис","value":"Steam"},{"label":"Тип","value":"Пополнение баланса"},{"label":"Зачисление в Steam","value":"1000 RUB"}],"fulfillment":{"title":"Данные пополнения Steam","description":"Логин Steam фиксируется в заказе. Зачисление будет выполняться provider-адаптером после подключения SIH fulfillment.","requirements":["Проверьте логин Steam перед оплатой.","Стоимость фиксируется в Coins по курсу Vault.","Перед отправкой провайдеру заказ пройдет повторную проверку статуса."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-06-02T10:00:00.000Z'
),
(
  'steam-top-up-2000',
  'steam-top-up-2000-rub',
  'steam',
  'Steam',
  'Steam',
  'Пополнение баланса',
  'Пополнение Steam на 2000 RUB',
  'Пополнение кошелька Steam на 2000 RUB. Стоимость фиксируется в Coins, логин сохраняется в заказе.',
  300000,
  'available',
  'automatic',
  84,
  NULL,
  NULL,
  ARRAY['1 RUB = 1.5 Coins', 'Steam', 'RUB'],
  ARRAY['стим', 'кошелек', 'баланс', 'пополнение'],
  '{"specifications":[{"label":"Сервис","value":"Steam"},{"label":"Тип","value":"Пополнение баланса"},{"label":"Зачисление в Steam","value":"2000 RUB"}],"fulfillment":{"title":"Данные пополнения Steam","description":"Логин Steam фиксируется в заказе. Зачисление будет выполняться provider-адаптером после подключения SIH fulfillment.","requirements":["Проверьте логин Steam перед оплатой.","Стоимость фиксируется в Coins по курсу Vault.","Перед отправкой провайдеру заказ пройдет повторную проверку статуса."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-06-20T10:00:00.000Z'
),
(
  'steam-top-up-5000',
  'steam-top-up-5000-rub',
  'steam',
  'Steam',
  'Steam',
  'Пополнение баланса',
  'Пополнение Steam на 5000 RUB',
  'Пополнение кошелька Steam на 5000 RUB с расчетом по курсу Vault.',
  750000,
  'available',
  'automatic',
  78,
  NULL,
  NULL,
  ARRAY['1 RUB = 1.5 Coins', 'Steam', 'RUB'],
  ARRAY['стим', 'кошелек', 'баланс', 'пополнение'],
  '{"specifications":[{"label":"Сервис","value":"Steam"},{"label":"Тип","value":"Пополнение баланса"},{"label":"Зачисление в Steam","value":"5000 RUB"}],"fulfillment":{"title":"Данные пополнения Steam","description":"Логин Steam фиксируется в заказе. Зачисление будет выполняться provider-адаптером после подключения SIH fulfillment.","requirements":["Проверьте логин Steam перед оплатой.","Стоимость фиксируется в Coins по курсу Vault.","Перед отправкой провайдеру заказ пройдет повторную проверку статуса."]}}'::jsonb,
  'seed',
  '{}'::jsonb,
  true,
  '2026-07-01T10:00:00.000Z'
)
ON CONFLICT ("id") DO NOTHING;
